### PR TITLE
Issue 31

### PR DESCRIPTION
**Pull request by MikeVaz**
Added state management similar to what we use in ZSUI. 
I am using ES6 modules. I think it will be nice for us to explore this considering 2019 roadmap.
It will be nice if we could update our UI to align with component-based architecture and split it into modules/components.

### CODE REVIEW

**Comment by php1990** [comment]
I see a blank page (without any console errors) upon opening state.html. Work in progress?

**Comment by MikeVaz** [comment]
> I see a blank page (without any console errors) upon opening state.html. Work in progress?

@php1990 this is because I use ES6 modules there and it requires to run a local server instead of using file:/// protocol. Cross-origin rules and MIME times in the context of serving from filesystem :(

**Comment by MikeVaz** [comment]
> I see a blank page (without any console errors) upon opening state.html. Work in progress?

@php1990 this is because I use ES6 modules there and it requires to run a local server instead of using file:/// protocol. Cross-origin rules and MIME times in the context of serving from filesystem :(

**Comment by MikeVaz** [comment]
> I see a blank page (without any console errors) upon opening state.html. Work in progress?

@php1990 this is because I use ES6 modules there and it requires to run a local server instead of using file:/// protocol. Cross-origin rules and MIME times in the context of serving from filesystem :(

**Comment by php1990** [comment]
> > I see a blank page (without any console errors) upon opening state.html. Work in progress?
> 
> @php1990 this is because I use ES6 modules there and it requires to run a local server instead of using file:/// protocol. Cross-origin rules and MIME times in the context of serving from filesystem :(

**Comment by php1990** [comment]
@MikeVaz yeah I had realized that upon encountering console error, so tried running on a local server too. But the page appeared blank again.

**Pull request merged**
